#!/usr/bin/python
# coding:utf-8
#
# Preparation
#
# 1. Install Python 3.*.* 64-bit ver
# - http://www.python.org
#
# 2. Download the following libraries.
# - numpy-*.*.*+mkl-cp*-cp*m-win_amd64.whl
# - scipy-*.*.*-cp*-cp*m-win_amd64.whl
# - scikit_learn-*.*.*-cp*-cp*m-win_amd64.whl
# -- http://www.lfd.uci.edu/~gohlke/pythonlibs/
# -- cp35 means for Python 3.5.*
#
# 3. Execute the following command.
# - python -m pip install --upgrade pip
# - pip install numpy-*.*.*+mkl-cp*-cp*m-win_amd64.whl scipy-*.*.*-cp*-cp*m-win_amd64.whl scikit_learn-*.*.*-cp*-cp*m-win_amd64.whl

import argparse
import bayes_opt
import collections
import datetime
import os
import pickle
import re
import scipy.stats
import subprocess
import sys
import time

START_COUNTER = 0
CURRENT_COUNTER = 0
MAX_EVALS = 10000
START_TIME_SEC = time.time()
EVAL_DIR = r'eval\2017-01-24-19-49-24\500000000'
ENGINE1 = r'YaneuraOu-2017-early-master.exe'
ENGINE2 = r'YaneuraOu-2017-early-slave.exe'
NUM_THREADS = 24
THINKING_TIME_MS = 10000
NUM_NUMA_NODES = 1
HASH = 256
PARAMETER_FILE_PATH = 'param/2017-early-param-master.h'
STATE = collections.defaultdict(list)
STATE_FILE_NAME = 'tanuki_optimizer2_state.pickle'


# パラメーターヘッダーファイルを生成する
def WriteHeaderFile(
  PARAM_FUTILITY_MARGIN_ALPHA_OPENING,
  PARAM_FUTILITY_MARGIN_ALPHA_ENDING,
  PARAM_FUTILITY_MARGIN_BETA_OPENING,
  PARAM_FUTILITY_MARGIN_BETA_ENDING,
  PARAM_FUTILITY_MARGIN_QUIET_OPENING,
  PARAM_FUTILITY_MARGIN_QUIET_ENDING,
  PARAM_FUTILITY_RETURN_DEPTH_OPENING,
  PARAM_FUTILITY_RETURN_DEPTH_ENDING,
  PARAM_FUTILITY_AT_PARENT_NODE_DEPTH_OPENING,
  PARAM_FUTILITY_AT_PARENT_NODE_DEPTH_ENDING,
  PARAM_FUTILITY_AT_PARENT_NODE_MARGIN1_OPENING,
  PARAM_FUTILITY_AT_PARENT_NODE_MARGIN1_ENDING,
  PARAM_FUTILITY_AT_PARENT_NODE_MARGIN2_OPENING,
  PARAM_FUTILITY_AT_PARENT_NODE_MARGIN2_ENDING,
  PARAM_FUTILITY_AT_PARENT_NODE_GAMMA1_OPENING,
  PARAM_FUTILITY_AT_PARENT_NODE_GAMMA1_ENDING,
  PARAM_FUTILITY_AT_PARENT_NODE_GAMMA2_OPENING,
  PARAM_FUTILITY_AT_PARENT_NODE_GAMMA2_ENDING,
  PARAM_NULL_MOVE_DYNAMIC_ALPHA_OPENING,
  PARAM_NULL_MOVE_DYNAMIC_ALPHA_ENDING,
  PARAM_NULL_MOVE_DYNAMIC_BETA_OPENING,
  PARAM_NULL_MOVE_DYNAMIC_BETA_ENDING,
  PARAM_NULL_MOVE_MARGIN_OPENING,
  PARAM_NULL_MOVE_MARGIN_ENDING,
  PARAM_NULL_MOVE_RETURN_DEPTH_OPENING,
  PARAM_NULL_MOVE_RETURN_DEPTH_ENDING,
  PARAM_PROBCUT_DEPTH_OPENING,
  PARAM_PROBCUT_DEPTH_ENDING,
  PARAM_PROBCUT_MARGIN_OPENING,
  PARAM_PROBCUT_MARGIN_ENDING,
  PARAM_SINGULAR_EXTENSION_DEPTH_OPENING,
  PARAM_SINGULAR_EXTENSION_DEPTH_ENDING,
  PARAM_SINGULAR_MARGIN_OPENING,
  PARAM_SINGULAR_MARGIN_ENDING,
  PARAM_SINGULAR_SEARCH_DEPTH_ALPHA_OPENING,
  PARAM_SINGULAR_SEARCH_DEPTH_ALPHA_ENDING,
  PARAM_PRUNING_BY_MOVE_COUNT_DEPTH_OPENING,
  PARAM_PRUNING_BY_MOVE_COUNT_DEPTH_ENDING,
  PARAM_PRUNING_BY_HISTORY_DEPTH_OPENING,
  PARAM_PRUNING_BY_HISTORY_DEPTH_ENDING,
  PARAM_REDUCTION_BY_HISTORY_OPENING,
  PARAM_REDUCTION_BY_HISTORY_ENDING,
  PARAM_IID_MARGIN_ALPHA_OPENING,
  PARAM_IID_MARGIN_ALPHA_ENDING,
  PARAM_RAZORING_MARGIN1_OPENING,
  PARAM_RAZORING_MARGIN1_ENDING,
  PARAM_RAZORING_MARGIN2_OPENING,
  PARAM_RAZORING_MARGIN2_ENDING,
  PARAM_RAZORING_MARGIN3_OPENING,
  PARAM_RAZORING_MARGIN3_ENDING,
  PARAM_RAZORING_MARGIN4_OPENING,
  PARAM_RAZORING_MARGIN4_ENDING,
  PARAM_REDUCTION_ALPHA_OPENING,
  PARAM_REDUCTION_ALPHA_ENDING,
  PARAM_FUTILITY_MOVE_COUNT_ALPHA0_OPENING,
  PARAM_FUTILITY_MOVE_COUNT_ALPHA0_ENDING,
  PARAM_FUTILITY_MOVE_COUNT_ALPHA1_OPENING,
  PARAM_FUTILITY_MOVE_COUNT_ALPHA1_ENDING,
  PARAM_FUTILITY_MOVE_COUNT_BETA0_OPENING,
  PARAM_FUTILITY_MOVE_COUNT_BETA0_ENDING,
  PARAM_FUTILITY_MOVE_COUNT_BETA1_OPENING,
  PARAM_FUTILITY_MOVE_COUNT_BETA1_ENDING,
  PARAM_QUIET_SEARCH_COUNT_OPENING,
  PARAM_QUIET_SEARCH_COUNT_ENDING,
  PARAM_QSEARCH_MATE1_OPENING,
  PARAM_QSEARCH_MATE1_ENDING,
  PARAM_SEARCH_MATE1_OPENING,
  PARAM_SEARCH_MATE1_ENDING,
  PARAM_WEAK_MATE_PLY_OPENING,
  PARAM_WEAK_MATE_PLY_ENDING):
  with open(PARAMETER_FILE_PATH, 'w') as f:
    f.write('#ifndef _2017_EARLY_PARAMETERS_\n')
    f.write('#define _2017_EARLY_PARAMETERS_\n')
    f.write('PARAM_DEFINE PARAM_FUTILITY_MARGIN_ALPHA_OPENING = {PARAM_FUTILITY_MARGIN_ALPHA_OPENING};\n'.format(PARAM_FUTILITY_MARGIN_ALPHA_OPENING=int(round(scipy.stats.norm.ppf(PARAM_FUTILITY_MARGIN_ALPHA_OPENING, loc=150, scale=23.3333333333)))))
    f.write('PARAM_DEFINE PARAM_FUTILITY_MARGIN_ALPHA_ENDING = {PARAM_FUTILITY_MARGIN_ALPHA_ENDING};\n'.format(PARAM_FUTILITY_MARGIN_ALPHA_ENDING=int(round(scipy.stats.norm.ppf(PARAM_FUTILITY_MARGIN_ALPHA_ENDING, loc=150, scale=1e-08)))))
    f.write('PARAM_DEFINE PARAM_FUTILITY_MARGIN_BETA_OPENING = {PARAM_FUTILITY_MARGIN_BETA_OPENING};\n'.format(PARAM_FUTILITY_MARGIN_BETA_OPENING=int(round(scipy.stats.norm.ppf(PARAM_FUTILITY_MARGIN_BETA_OPENING, loc=200, scale=23.3333333333)))))
    f.write('PARAM_DEFINE PARAM_FUTILITY_MARGIN_BETA_ENDING = {PARAM_FUTILITY_MARGIN_BETA_ENDING};\n'.format(PARAM_FUTILITY_MARGIN_BETA_ENDING=int(round(scipy.stats.norm.ppf(PARAM_FUTILITY_MARGIN_BETA_ENDING, loc=200, scale=1e-08)))))
    f.write('PARAM_DEFINE PARAM_FUTILITY_MARGIN_QUIET_OPENING = {PARAM_FUTILITY_MARGIN_QUIET_OPENING};\n'.format(PARAM_FUTILITY_MARGIN_QUIET_OPENING=int(round(scipy.stats.norm.ppf(PARAM_FUTILITY_MARGIN_QUIET_OPENING, loc=128, scale=18.3333333333)))))
    f.write('PARAM_DEFINE PARAM_FUTILITY_MARGIN_QUIET_ENDING = {PARAM_FUTILITY_MARGIN_QUIET_ENDING};\n'.format(PARAM_FUTILITY_MARGIN_QUIET_ENDING=int(round(scipy.stats.norm.ppf(PARAM_FUTILITY_MARGIN_QUIET_ENDING, loc=128, scale=1e-08)))))
    f.write('PARAM_DEFINE PARAM_FUTILITY_RETURN_DEPTH_OPENING = {PARAM_FUTILITY_RETURN_DEPTH_OPENING};\n'.format(PARAM_FUTILITY_RETURN_DEPTH_OPENING=int(round(scipy.stats.norm.ppf(PARAM_FUTILITY_RETURN_DEPTH_OPENING, loc=7, scale=1.33333333333)))))
    f.write('PARAM_DEFINE PARAM_FUTILITY_RETURN_DEPTH_ENDING = {PARAM_FUTILITY_RETURN_DEPTH_ENDING};\n'.format(PARAM_FUTILITY_RETURN_DEPTH_ENDING=int(round(scipy.stats.norm.ppf(PARAM_FUTILITY_RETURN_DEPTH_ENDING, loc=7, scale=1e-08)))))
    f.write('PARAM_DEFINE PARAM_FUTILITY_AT_PARENT_NODE_DEPTH_OPENING = {PARAM_FUTILITY_AT_PARENT_NODE_DEPTH_OPENING};\n'.format(PARAM_FUTILITY_AT_PARENT_NODE_DEPTH_OPENING=int(round(scipy.stats.norm.ppf(PARAM_FUTILITY_AT_PARENT_NODE_DEPTH_OPENING, loc=7, scale=1.33333333333)))))
    f.write('PARAM_DEFINE PARAM_FUTILITY_AT_PARENT_NODE_DEPTH_ENDING = {PARAM_FUTILITY_AT_PARENT_NODE_DEPTH_ENDING};\n'.format(PARAM_FUTILITY_AT_PARENT_NODE_DEPTH_ENDING=int(round(scipy.stats.norm.ppf(PARAM_FUTILITY_AT_PARENT_NODE_DEPTH_ENDING, loc=7, scale=1e-08)))))
    f.write('PARAM_DEFINE PARAM_FUTILITY_AT_PARENT_NODE_MARGIN1_OPENING = {PARAM_FUTILITY_AT_PARENT_NODE_MARGIN1_OPENING};\n'.format(PARAM_FUTILITY_AT_PARENT_NODE_MARGIN1_OPENING=int(round(scipy.stats.norm.ppf(PARAM_FUTILITY_AT_PARENT_NODE_MARGIN1_OPENING, loc=256, scale=33.3333333333)))))
    f.write('PARAM_DEFINE PARAM_FUTILITY_AT_PARENT_NODE_MARGIN1_ENDING = {PARAM_FUTILITY_AT_PARENT_NODE_MARGIN1_ENDING};\n'.format(PARAM_FUTILITY_AT_PARENT_NODE_MARGIN1_ENDING=int(round(scipy.stats.norm.ppf(PARAM_FUTILITY_AT_PARENT_NODE_MARGIN1_ENDING, loc=256, scale=1e-08)))))
    f.write('PARAM_DEFINE PARAM_FUTILITY_AT_PARENT_NODE_MARGIN2_OPENING = {PARAM_FUTILITY_AT_PARENT_NODE_MARGIN2_OPENING};\n'.format(PARAM_FUTILITY_AT_PARENT_NODE_MARGIN2_OPENING=int(round(scipy.stats.norm.ppf(PARAM_FUTILITY_AT_PARENT_NODE_MARGIN2_OPENING, loc=200, scale=50.0)))))
    f.write('PARAM_DEFINE PARAM_FUTILITY_AT_PARENT_NODE_MARGIN2_ENDING = {PARAM_FUTILITY_AT_PARENT_NODE_MARGIN2_ENDING};\n'.format(PARAM_FUTILITY_AT_PARENT_NODE_MARGIN2_ENDING=int(round(scipy.stats.norm.ppf(PARAM_FUTILITY_AT_PARENT_NODE_MARGIN2_ENDING, loc=200, scale=1e-08)))))
    f.write('PARAM_DEFINE PARAM_FUTILITY_AT_PARENT_NODE_GAMMA1_OPENING = {PARAM_FUTILITY_AT_PARENT_NODE_GAMMA1_OPENING};\n'.format(PARAM_FUTILITY_AT_PARENT_NODE_GAMMA1_OPENING=int(round(scipy.stats.norm.ppf(PARAM_FUTILITY_AT_PARENT_NODE_GAMMA1_OPENING, loc=35, scale=5.0)))))
    f.write('PARAM_DEFINE PARAM_FUTILITY_AT_PARENT_NODE_GAMMA1_ENDING = {PARAM_FUTILITY_AT_PARENT_NODE_GAMMA1_ENDING};\n'.format(PARAM_FUTILITY_AT_PARENT_NODE_GAMMA1_ENDING=int(round(scipy.stats.norm.ppf(PARAM_FUTILITY_AT_PARENT_NODE_GAMMA1_ENDING, loc=35, scale=1e-08)))))
    f.write('PARAM_DEFINE PARAM_FUTILITY_AT_PARENT_NODE_GAMMA2_OPENING = {PARAM_FUTILITY_AT_PARENT_NODE_GAMMA2_OPENING};\n'.format(PARAM_FUTILITY_AT_PARENT_NODE_GAMMA2_OPENING=int(round(scipy.stats.norm.ppf(PARAM_FUTILITY_AT_PARENT_NODE_GAMMA2_OPENING, loc=35, scale=6.66666666667)))))
    f.write('PARAM_DEFINE PARAM_FUTILITY_AT_PARENT_NODE_GAMMA2_ENDING = {PARAM_FUTILITY_AT_PARENT_NODE_GAMMA2_ENDING};\n'.format(PARAM_FUTILITY_AT_PARENT_NODE_GAMMA2_ENDING=int(round(scipy.stats.norm.ppf(PARAM_FUTILITY_AT_PARENT_NODE_GAMMA2_ENDING, loc=35, scale=1e-08)))))
    f.write('PARAM_DEFINE PARAM_NULL_MOVE_DYNAMIC_ALPHA_OPENING = {PARAM_NULL_MOVE_DYNAMIC_ALPHA_OPENING};\n'.format(PARAM_NULL_MOVE_DYNAMIC_ALPHA_OPENING=int(round(scipy.stats.norm.ppf(PARAM_NULL_MOVE_DYNAMIC_ALPHA_OPENING, loc=823, scale=166.666666667)))))
    f.write('PARAM_DEFINE PARAM_NULL_MOVE_DYNAMIC_ALPHA_ENDING = {PARAM_NULL_MOVE_DYNAMIC_ALPHA_ENDING};\n'.format(PARAM_NULL_MOVE_DYNAMIC_ALPHA_ENDING=int(round(scipy.stats.norm.ppf(PARAM_NULL_MOVE_DYNAMIC_ALPHA_ENDING, loc=823, scale=1e-08)))))
    f.write('PARAM_DEFINE PARAM_NULL_MOVE_DYNAMIC_BETA_OPENING = {PARAM_NULL_MOVE_DYNAMIC_BETA_OPENING};\n'.format(PARAM_NULL_MOVE_DYNAMIC_BETA_OPENING=int(round(scipy.stats.norm.ppf(PARAM_NULL_MOVE_DYNAMIC_BETA_OPENING, loc=67, scale=8.33333333333)))))
    f.write('PARAM_DEFINE PARAM_NULL_MOVE_DYNAMIC_BETA_ENDING = {PARAM_NULL_MOVE_DYNAMIC_BETA_ENDING};\n'.format(PARAM_NULL_MOVE_DYNAMIC_BETA_ENDING=int(round(scipy.stats.norm.ppf(PARAM_NULL_MOVE_DYNAMIC_BETA_ENDING, loc=67, scale=1e-08)))))
    f.write('PARAM_DEFINE PARAM_NULL_MOVE_MARGIN_OPENING = {PARAM_NULL_MOVE_MARGIN_OPENING};\n'.format(PARAM_NULL_MOVE_MARGIN_OPENING=int(round(scipy.stats.norm.ppf(PARAM_NULL_MOVE_MARGIN_OPENING, loc=35, scale=8.33333333333)))))
    f.write('PARAM_DEFINE PARAM_NULL_MOVE_MARGIN_ENDING = {PARAM_NULL_MOVE_MARGIN_ENDING};\n'.format(PARAM_NULL_MOVE_MARGIN_ENDING=int(round(scipy.stats.norm.ppf(PARAM_NULL_MOVE_MARGIN_ENDING, loc=35, scale=1e-08)))))
    f.write('PARAM_DEFINE PARAM_NULL_MOVE_RETURN_DEPTH_OPENING = {PARAM_NULL_MOVE_RETURN_DEPTH_OPENING};\n'.format(PARAM_NULL_MOVE_RETURN_DEPTH_OPENING=int(round(scipy.stats.norm.ppf(PARAM_NULL_MOVE_RETURN_DEPTH_OPENING, loc=12, scale=1.83333333333)))))
    f.write('PARAM_DEFINE PARAM_NULL_MOVE_RETURN_DEPTH_ENDING = {PARAM_NULL_MOVE_RETURN_DEPTH_ENDING};\n'.format(PARAM_NULL_MOVE_RETURN_DEPTH_ENDING=int(round(scipy.stats.norm.ppf(PARAM_NULL_MOVE_RETURN_DEPTH_ENDING, loc=12, scale=1e-08)))))
    f.write('PARAM_DEFINE PARAM_PROBCUT_DEPTH_OPENING = {PARAM_PROBCUT_DEPTH_OPENING};\n'.format(PARAM_PROBCUT_DEPTH_OPENING=int(round(scipy.stats.norm.ppf(PARAM_PROBCUT_DEPTH_OPENING, loc=5, scale=1.16666666667)))))
    f.write('PARAM_DEFINE PARAM_PROBCUT_DEPTH_ENDING = {PARAM_PROBCUT_DEPTH_ENDING};\n'.format(PARAM_PROBCUT_DEPTH_ENDING=int(round(scipy.stats.norm.ppf(PARAM_PROBCUT_DEPTH_ENDING, loc=5, scale=1e-08)))))
    f.write('PARAM_DEFINE PARAM_PROBCUT_MARGIN_OPENING = {PARAM_PROBCUT_MARGIN_OPENING};\n'.format(PARAM_PROBCUT_MARGIN_OPENING=int(round(scipy.stats.norm.ppf(PARAM_PROBCUT_MARGIN_OPENING, loc=200, scale=33.3333333333)))))
    f.write('PARAM_DEFINE PARAM_PROBCUT_MARGIN_ENDING = {PARAM_PROBCUT_MARGIN_ENDING};\n'.format(PARAM_PROBCUT_MARGIN_ENDING=int(round(scipy.stats.norm.ppf(PARAM_PROBCUT_MARGIN_ENDING, loc=200, scale=1e-08)))))
    f.write('PARAM_DEFINE PARAM_SINGULAR_EXTENSION_DEPTH_OPENING = {PARAM_SINGULAR_EXTENSION_DEPTH_OPENING};\n'.format(PARAM_SINGULAR_EXTENSION_DEPTH_OPENING=int(round(scipy.stats.norm.ppf(PARAM_SINGULAR_EXTENSION_DEPTH_OPENING, loc=8, scale=1.5)))))
    f.write('PARAM_DEFINE PARAM_SINGULAR_EXTENSION_DEPTH_ENDING = {PARAM_SINGULAR_EXTENSION_DEPTH_ENDING};\n'.format(PARAM_SINGULAR_EXTENSION_DEPTH_ENDING=int(round(scipy.stats.norm.ppf(PARAM_SINGULAR_EXTENSION_DEPTH_ENDING, loc=8, scale=1e-08)))))
    f.write('PARAM_DEFINE PARAM_SINGULAR_MARGIN_OPENING = {PARAM_SINGULAR_MARGIN_OPENING};\n'.format(PARAM_SINGULAR_MARGIN_OPENING=int(round(scipy.stats.norm.ppf(PARAM_SINGULAR_MARGIN_OPENING, loc=256, scale=45.3333333333)))))
    f.write('PARAM_DEFINE PARAM_SINGULAR_MARGIN_ENDING = {PARAM_SINGULAR_MARGIN_ENDING};\n'.format(PARAM_SINGULAR_MARGIN_ENDING=int(round(scipy.stats.norm.ppf(PARAM_SINGULAR_MARGIN_ENDING, loc=256, scale=1e-08)))))
    f.write('PARAM_DEFINE PARAM_SINGULAR_SEARCH_DEPTH_ALPHA_OPENING = {PARAM_SINGULAR_SEARCH_DEPTH_ALPHA_OPENING};\n'.format(PARAM_SINGULAR_SEARCH_DEPTH_ALPHA_OPENING=int(round(scipy.stats.norm.ppf(PARAM_SINGULAR_SEARCH_DEPTH_ALPHA_OPENING, loc=16, scale=4.0)))))
    f.write('PARAM_DEFINE PARAM_SINGULAR_SEARCH_DEPTH_ALPHA_ENDING = {PARAM_SINGULAR_SEARCH_DEPTH_ALPHA_ENDING};\n'.format(PARAM_SINGULAR_SEARCH_DEPTH_ALPHA_ENDING=int(round(scipy.stats.norm.ppf(PARAM_SINGULAR_SEARCH_DEPTH_ALPHA_ENDING, loc=16, scale=1e-08)))))
    f.write('PARAM_DEFINE PARAM_PRUNING_BY_MOVE_COUNT_DEPTH_OPENING = {PARAM_PRUNING_BY_MOVE_COUNT_DEPTH_OPENING};\n'.format(PARAM_PRUNING_BY_MOVE_COUNT_DEPTH_OPENING=int(round(scipy.stats.norm.ppf(PARAM_PRUNING_BY_MOVE_COUNT_DEPTH_OPENING, loc=16, scale=4.0)))))
    f.write('PARAM_DEFINE PARAM_PRUNING_BY_MOVE_COUNT_DEPTH_ENDING = {PARAM_PRUNING_BY_MOVE_COUNT_DEPTH_ENDING};\n'.format(PARAM_PRUNING_BY_MOVE_COUNT_DEPTH_ENDING=int(round(scipy.stats.norm.ppf(PARAM_PRUNING_BY_MOVE_COUNT_DEPTH_ENDING, loc=16, scale=1e-08)))))
    f.write('PARAM_DEFINE PARAM_PRUNING_BY_HISTORY_DEPTH_OPENING = {PARAM_PRUNING_BY_HISTORY_DEPTH_OPENING};\n'.format(PARAM_PRUNING_BY_HISTORY_DEPTH_OPENING=int(round(scipy.stats.norm.ppf(PARAM_PRUNING_BY_HISTORY_DEPTH_OPENING, loc=3, scale=5.0)))))
    f.write('PARAM_DEFINE PARAM_PRUNING_BY_HISTORY_DEPTH_ENDING = {PARAM_PRUNING_BY_HISTORY_DEPTH_ENDING};\n'.format(PARAM_PRUNING_BY_HISTORY_DEPTH_ENDING=int(round(scipy.stats.norm.ppf(PARAM_PRUNING_BY_HISTORY_DEPTH_ENDING, loc=3, scale=1e-08)))))
    f.write('PARAM_DEFINE PARAM_REDUCTION_BY_HISTORY_OPENING = {PARAM_REDUCTION_BY_HISTORY_OPENING};\n'.format(PARAM_REDUCTION_BY_HISTORY_OPENING=int(round(scipy.stats.norm.ppf(PARAM_REDUCTION_BY_HISTORY_OPENING, loc=8000, scale=1833.33333333)))))
    f.write('PARAM_DEFINE PARAM_REDUCTION_BY_HISTORY_ENDING = {PARAM_REDUCTION_BY_HISTORY_ENDING};\n'.format(PARAM_REDUCTION_BY_HISTORY_ENDING=int(round(scipy.stats.norm.ppf(PARAM_REDUCTION_BY_HISTORY_ENDING, loc=8000, scale=1e-08)))))
    f.write('PARAM_DEFINE PARAM_IID_MARGIN_ALPHA_OPENING = {PARAM_IID_MARGIN_ALPHA_OPENING};\n'.format(PARAM_IID_MARGIN_ALPHA_OPENING=int(round(scipy.stats.norm.ppf(PARAM_IID_MARGIN_ALPHA_OPENING, loc=256, scale=42.6666666667)))))
    f.write('PARAM_DEFINE PARAM_IID_MARGIN_ALPHA_ENDING = {PARAM_IID_MARGIN_ALPHA_ENDING};\n'.format(PARAM_IID_MARGIN_ALPHA_ENDING=int(round(scipy.stats.norm.ppf(PARAM_IID_MARGIN_ALPHA_ENDING, loc=256, scale=1e-08)))))
    f.write('PARAM_DEFINE PARAM_RAZORING_MARGIN1_OPENING = {PARAM_RAZORING_MARGIN1_OPENING};\n'.format(PARAM_RAZORING_MARGIN1_OPENING=int(round(scipy.stats.norm.ppf(PARAM_RAZORING_MARGIN1_OPENING, loc=483, scale=50.0)))))
    f.write('PARAM_DEFINE PARAM_RAZORING_MARGIN1_ENDING = {PARAM_RAZORING_MARGIN1_ENDING};\n'.format(PARAM_RAZORING_MARGIN1_ENDING=int(round(scipy.stats.norm.ppf(PARAM_RAZORING_MARGIN1_ENDING, loc=483, scale=1e-08)))))
    f.write('PARAM_DEFINE PARAM_RAZORING_MARGIN2_OPENING = {PARAM_RAZORING_MARGIN2_OPENING};\n'.format(PARAM_RAZORING_MARGIN2_OPENING=int(round(scipy.stats.norm.ppf(PARAM_RAZORING_MARGIN2_OPENING, loc=570, scale=50.0)))))
    f.write('PARAM_DEFINE PARAM_RAZORING_MARGIN2_ENDING = {PARAM_RAZORING_MARGIN2_ENDING};\n'.format(PARAM_RAZORING_MARGIN2_ENDING=int(round(scipy.stats.norm.ppf(PARAM_RAZORING_MARGIN2_ENDING, loc=570, scale=1e-08)))))
    f.write('PARAM_DEFINE PARAM_RAZORING_MARGIN3_OPENING = {PARAM_RAZORING_MARGIN3_OPENING};\n'.format(PARAM_RAZORING_MARGIN3_OPENING=int(round(scipy.stats.norm.ppf(PARAM_RAZORING_MARGIN3_OPENING, loc=603, scale=50.0)))))
    f.write('PARAM_DEFINE PARAM_RAZORING_MARGIN3_ENDING = {PARAM_RAZORING_MARGIN3_ENDING};\n'.format(PARAM_RAZORING_MARGIN3_ENDING=int(round(scipy.stats.norm.ppf(PARAM_RAZORING_MARGIN3_ENDING, loc=603, scale=1e-08)))))
    f.write('PARAM_DEFINE PARAM_RAZORING_MARGIN4_OPENING = {PARAM_RAZORING_MARGIN4_OPENING};\n'.format(PARAM_RAZORING_MARGIN4_OPENING=int(round(scipy.stats.norm.ppf(PARAM_RAZORING_MARGIN4_OPENING, loc=554, scale=50.0)))))
    f.write('PARAM_DEFINE PARAM_RAZORING_MARGIN4_ENDING = {PARAM_RAZORING_MARGIN4_ENDING};\n'.format(PARAM_RAZORING_MARGIN4_ENDING=int(round(scipy.stats.norm.ppf(PARAM_RAZORING_MARGIN4_ENDING, loc=554, scale=1e-08)))))
    f.write('PARAM_DEFINE PARAM_REDUCTION_ALPHA_OPENING = {PARAM_REDUCTION_ALPHA_OPENING};\n'.format(PARAM_REDUCTION_ALPHA_OPENING=int(round(scipy.stats.norm.ppf(PARAM_REDUCTION_ALPHA_OPENING, loc=128, scale=32.0)))))
    f.write('PARAM_DEFINE PARAM_REDUCTION_ALPHA_ENDING = {PARAM_REDUCTION_ALPHA_ENDING};\n'.format(PARAM_REDUCTION_ALPHA_ENDING=int(round(scipy.stats.norm.ppf(PARAM_REDUCTION_ALPHA_ENDING, loc=128, scale=1e-08)))))
    f.write('PARAM_DEFINE PARAM_FUTILITY_MOVE_COUNT_ALPHA0_OPENING = {PARAM_FUTILITY_MOVE_COUNT_ALPHA0_OPENING};\n'.format(PARAM_FUTILITY_MOVE_COUNT_ALPHA0_OPENING=int(round(scipy.stats.norm.ppf(PARAM_FUTILITY_MOVE_COUNT_ALPHA0_OPENING, loc=240, scale=41.6666666667)))))
    f.write('PARAM_DEFINE PARAM_FUTILITY_MOVE_COUNT_ALPHA0_ENDING = {PARAM_FUTILITY_MOVE_COUNT_ALPHA0_ENDING};\n'.format(PARAM_FUTILITY_MOVE_COUNT_ALPHA0_ENDING=int(round(scipy.stats.norm.ppf(PARAM_FUTILITY_MOVE_COUNT_ALPHA0_ENDING, loc=240, scale=1e-08)))))
    f.write('PARAM_DEFINE PARAM_FUTILITY_MOVE_COUNT_ALPHA1_OPENING = {PARAM_FUTILITY_MOVE_COUNT_ALPHA1_OPENING};\n'.format(PARAM_FUTILITY_MOVE_COUNT_ALPHA1_OPENING=int(round(scipy.stats.norm.ppf(PARAM_FUTILITY_MOVE_COUNT_ALPHA1_OPENING, loc=290, scale=41.6666666667)))))
    f.write('PARAM_DEFINE PARAM_FUTILITY_MOVE_COUNT_ALPHA1_ENDING = {PARAM_FUTILITY_MOVE_COUNT_ALPHA1_ENDING};\n'.format(PARAM_FUTILITY_MOVE_COUNT_ALPHA1_ENDING=int(round(scipy.stats.norm.ppf(PARAM_FUTILITY_MOVE_COUNT_ALPHA1_ENDING, loc=290, scale=1e-08)))))
    f.write('PARAM_DEFINE PARAM_FUTILITY_MOVE_COUNT_BETA0_OPENING = {PARAM_FUTILITY_MOVE_COUNT_BETA0_OPENING};\n'.format(PARAM_FUTILITY_MOVE_COUNT_BETA0_OPENING=int(round(scipy.stats.norm.ppf(PARAM_FUTILITY_MOVE_COUNT_BETA0_OPENING, loc=773, scale=250.0)))))
    f.write('PARAM_DEFINE PARAM_FUTILITY_MOVE_COUNT_BETA0_ENDING = {PARAM_FUTILITY_MOVE_COUNT_BETA0_ENDING};\n'.format(PARAM_FUTILITY_MOVE_COUNT_BETA0_ENDING=int(round(scipy.stats.norm.ppf(PARAM_FUTILITY_MOVE_COUNT_BETA0_ENDING, loc=773, scale=1e-08)))))
    f.write('PARAM_DEFINE PARAM_FUTILITY_MOVE_COUNT_BETA1_OPENING = {PARAM_FUTILITY_MOVE_COUNT_BETA1_OPENING};\n'.format(PARAM_FUTILITY_MOVE_COUNT_BETA1_OPENING=int(round(scipy.stats.norm.ppf(PARAM_FUTILITY_MOVE_COUNT_BETA1_OPENING, loc=1045, scale=250.0)))))
    f.write('PARAM_DEFINE PARAM_FUTILITY_MOVE_COUNT_BETA1_ENDING = {PARAM_FUTILITY_MOVE_COUNT_BETA1_ENDING};\n'.format(PARAM_FUTILITY_MOVE_COUNT_BETA1_ENDING=int(round(scipy.stats.norm.ppf(PARAM_FUTILITY_MOVE_COUNT_BETA1_ENDING, loc=1045, scale=1e-08)))))
    f.write('PARAM_DEFINE PARAM_QUIET_SEARCH_COUNT_OPENING = {PARAM_QUIET_SEARCH_COUNT_OPENING};\n'.format(PARAM_QUIET_SEARCH_COUNT_OPENING=int(round(scipy.stats.norm.ppf(PARAM_QUIET_SEARCH_COUNT_OPENING, loc=64, scale=16.0)))))
    f.write('PARAM_DEFINE PARAM_QUIET_SEARCH_COUNT_ENDING = {PARAM_QUIET_SEARCH_COUNT_ENDING};\n'.format(PARAM_QUIET_SEARCH_COUNT_ENDING=int(round(scipy.stats.norm.ppf(PARAM_QUIET_SEARCH_COUNT_ENDING, loc=64, scale=1e-08)))))
    f.write('PARAM_DEFINE PARAM_QSEARCH_MATE1_OPENING = {PARAM_QSEARCH_MATE1_OPENING};\n'.format(PARAM_QSEARCH_MATE1_OPENING=int(round(scipy.stats.norm.ppf(PARAM_QSEARCH_MATE1_OPENING, loc=1, scale=0.166666666667)))))
    f.write('PARAM_DEFINE PARAM_QSEARCH_MATE1_ENDING = {PARAM_QSEARCH_MATE1_ENDING};\n'.format(PARAM_QSEARCH_MATE1_ENDING=int(round(scipy.stats.norm.ppf(PARAM_QSEARCH_MATE1_ENDING, loc=1, scale=1e-08)))))
    f.write('PARAM_DEFINE PARAM_SEARCH_MATE1_OPENING = {PARAM_SEARCH_MATE1_OPENING};\n'.format(PARAM_SEARCH_MATE1_OPENING=int(round(scipy.stats.norm.ppf(PARAM_SEARCH_MATE1_OPENING, loc=1, scale=0.166666666667)))))
    f.write('PARAM_DEFINE PARAM_SEARCH_MATE1_ENDING = {PARAM_SEARCH_MATE1_ENDING};\n'.format(PARAM_SEARCH_MATE1_ENDING=int(round(scipy.stats.norm.ppf(PARAM_SEARCH_MATE1_ENDING, loc=1, scale=1e-08)))))
    f.write('PARAM_DEFINE PARAM_WEAK_MATE_PLY_OPENING = {PARAM_WEAK_MATE_PLY_OPENING};\n'.format(PARAM_WEAK_MATE_PLY_OPENING=int(round(scipy.stats.norm.ppf(PARAM_WEAK_MATE_PLY_OPENING, loc=1, scale=0.666666666667)))))
    f.write('PARAM_DEFINE PARAM_WEAK_MATE_PLY_ENDING = {PARAM_WEAK_MATE_PLY_ENDING};\n'.format(PARAM_WEAK_MATE_PLY_ENDING=int(round(scipy.stats.norm.ppf(PARAM_WEAK_MATE_PLY_ENDING, loc=1, scale=1e-08)))))
    f.write('#endif\n')


def Function(
  PARAM_FUTILITY_MARGIN_ALPHA_OPENING,
  PARAM_FUTILITY_MARGIN_ALPHA_ENDING,
  PARAM_FUTILITY_MARGIN_BETA_OPENING,
  PARAM_FUTILITY_MARGIN_BETA_ENDING,
  PARAM_FUTILITY_MARGIN_QUIET_OPENING,
  PARAM_FUTILITY_MARGIN_QUIET_ENDING,
  PARAM_FUTILITY_RETURN_DEPTH_OPENING,
  PARAM_FUTILITY_RETURN_DEPTH_ENDING,
  PARAM_FUTILITY_AT_PARENT_NODE_DEPTH_OPENING,
  PARAM_FUTILITY_AT_PARENT_NODE_DEPTH_ENDING,
  PARAM_FUTILITY_AT_PARENT_NODE_MARGIN1_OPENING,
  PARAM_FUTILITY_AT_PARENT_NODE_MARGIN1_ENDING,
  PARAM_FUTILITY_AT_PARENT_NODE_MARGIN2_OPENING,
  PARAM_FUTILITY_AT_PARENT_NODE_MARGIN2_ENDING,
  PARAM_FUTILITY_AT_PARENT_NODE_GAMMA1_OPENING,
  PARAM_FUTILITY_AT_PARENT_NODE_GAMMA1_ENDING,
  PARAM_FUTILITY_AT_PARENT_NODE_GAMMA2_OPENING,
  PARAM_FUTILITY_AT_PARENT_NODE_GAMMA2_ENDING,
  PARAM_NULL_MOVE_DYNAMIC_ALPHA_OPENING,
  PARAM_NULL_MOVE_DYNAMIC_ALPHA_ENDING,
  PARAM_NULL_MOVE_DYNAMIC_BETA_OPENING,
  PARAM_NULL_MOVE_DYNAMIC_BETA_ENDING,
  PARAM_NULL_MOVE_MARGIN_OPENING,
  PARAM_NULL_MOVE_MARGIN_ENDING,
  PARAM_NULL_MOVE_RETURN_DEPTH_OPENING,
  PARAM_NULL_MOVE_RETURN_DEPTH_ENDING,
  PARAM_PROBCUT_DEPTH_OPENING,
  PARAM_PROBCUT_DEPTH_ENDING,
  PARAM_PROBCUT_MARGIN_OPENING,
  PARAM_PROBCUT_MARGIN_ENDING,
  PARAM_SINGULAR_EXTENSION_DEPTH_OPENING,
  PARAM_SINGULAR_EXTENSION_DEPTH_ENDING,
  PARAM_SINGULAR_MARGIN_OPENING,
  PARAM_SINGULAR_MARGIN_ENDING,
  PARAM_SINGULAR_SEARCH_DEPTH_ALPHA_OPENING,
  PARAM_SINGULAR_SEARCH_DEPTH_ALPHA_ENDING,
  PARAM_PRUNING_BY_MOVE_COUNT_DEPTH_OPENING,
  PARAM_PRUNING_BY_MOVE_COUNT_DEPTH_ENDING,
  PARAM_PRUNING_BY_HISTORY_DEPTH_OPENING,
  PARAM_PRUNING_BY_HISTORY_DEPTH_ENDING,
  PARAM_REDUCTION_BY_HISTORY_OPENING,
  PARAM_REDUCTION_BY_HISTORY_ENDING,
  PARAM_IID_MARGIN_ALPHA_OPENING,
  PARAM_IID_MARGIN_ALPHA_ENDING,
  PARAM_RAZORING_MARGIN1_OPENING,
  PARAM_RAZORING_MARGIN1_ENDING,
  PARAM_RAZORING_MARGIN2_OPENING,
  PARAM_RAZORING_MARGIN2_ENDING,
  PARAM_RAZORING_MARGIN3_OPENING,
  PARAM_RAZORING_MARGIN3_ENDING,
  PARAM_RAZORING_MARGIN4_OPENING,
  PARAM_RAZORING_MARGIN4_ENDING,
  PARAM_REDUCTION_ALPHA_OPENING,
  PARAM_REDUCTION_ALPHA_ENDING,
  PARAM_FUTILITY_MOVE_COUNT_ALPHA0_OPENING,
  PARAM_FUTILITY_MOVE_COUNT_ALPHA0_ENDING,
  PARAM_FUTILITY_MOVE_COUNT_ALPHA1_OPENING,
  PARAM_FUTILITY_MOVE_COUNT_ALPHA1_ENDING,
  PARAM_FUTILITY_MOVE_COUNT_BETA0_OPENING,
  PARAM_FUTILITY_MOVE_COUNT_BETA0_ENDING,
  PARAM_FUTILITY_MOVE_COUNT_BETA1_OPENING,
  PARAM_FUTILITY_MOVE_COUNT_BETA1_ENDING,
  PARAM_QUIET_SEARCH_COUNT_OPENING,
  PARAM_QUIET_SEARCH_COUNT_ENDING,
  PARAM_QSEARCH_MATE1_OPENING,
  PARAM_QSEARCH_MATE1_ENDING,
  PARAM_SEARCH_MATE1_OPENING,
  PARAM_SEARCH_MATE1_ENDING,
  PARAM_WEAK_MATE_PLY_OPENING,
  PARAM_WEAK_MATE_PLY_ENDING):
  print('-' * 78)

  print(datetime.datetime.today().strftime("%Y-%m-%d %H:%M:%S"))

  global START_COUNTER
  global CURRENT_COUNTER
  global MAX_EVALS
  global START_TIME_SEC
  global EVAL_DIR
  global ENGINE1
  global ENGINE2
  global NUM_THREADS
  global THINKING_TIME_MS
  global NUM_NUMA_NODES
  global HASH
  global PARAMETER_FILE_PATH

  #print('PARAM_FUTILITY_MARGIN_ALPHA_OPENING               = {PARAM_FUTILITY_MARGIN_ALPHA_OPENING}'.format(PARAM_FUTILITY_MARGIN_ALPHA_OPENING=PARAM_FUTILITY_MARGIN_ALPHA_OPENING))
  #print('PARAM_FUTILITY_MARGIN_ALPHA_ENDING                = {PARAM_FUTILITY_MARGIN_ALPHA_ENDING}'.format(PARAM_FUTILITY_MARGIN_ALPHA_ENDING=PARAM_FUTILITY_MARGIN_ALPHA_ENDING))
  #print('PARAM_FUTILITY_MARGIN_BETA_OPENING                = {PARAM_FUTILITY_MARGIN_BETA_OPENING}'.format(PARAM_FUTILITY_MARGIN_BETA_OPENING=PARAM_FUTILITY_MARGIN_BETA_OPENING))
  #print('PARAM_FUTILITY_MARGIN_BETA_ENDING                 = {PARAM_FUTILITY_MARGIN_BETA_ENDING}'.format(PARAM_FUTILITY_MARGIN_BETA_ENDING=PARAM_FUTILITY_MARGIN_BETA_ENDING))
  #print('PARAM_FUTILITY_MARGIN_QUIET_OPENING               = {PARAM_FUTILITY_MARGIN_QUIET_OPENING}'.format(PARAM_FUTILITY_MARGIN_QUIET_OPENING=PARAM_FUTILITY_MARGIN_QUIET_OPENING))
  #print('PARAM_FUTILITY_MARGIN_QUIET_ENDING                = {PARAM_FUTILITY_MARGIN_QUIET_ENDING}'.format(PARAM_FUTILITY_MARGIN_QUIET_ENDING=PARAM_FUTILITY_MARGIN_QUIET_ENDING))
  #print('PARAM_FUTILITY_RETURN_DEPTH_OPENING               = {PARAM_FUTILITY_RETURN_DEPTH_OPENING}'.format(PARAM_FUTILITY_RETURN_DEPTH_OPENING=PARAM_FUTILITY_RETURN_DEPTH_OPENING))
  #print('PARAM_FUTILITY_RETURN_DEPTH_ENDING                = {PARAM_FUTILITY_RETURN_DEPTH_ENDING}'.format(PARAM_FUTILITY_RETURN_DEPTH_ENDING=PARAM_FUTILITY_RETURN_DEPTH_ENDING))
  #print('PARAM_FUTILITY_AT_PARENT_NODE_DEPTH_OPENING       = {PARAM_FUTILITY_AT_PARENT_NODE_DEPTH_OPENING}'.format(PARAM_FUTILITY_AT_PARENT_NODE_DEPTH_OPENING=PARAM_FUTILITY_AT_PARENT_NODE_DEPTH_OPENING))
  #print('PARAM_FUTILITY_AT_PARENT_NODE_DEPTH_ENDING        = {PARAM_FUTILITY_AT_PARENT_NODE_DEPTH_ENDING}'.format(PARAM_FUTILITY_AT_PARENT_NODE_DEPTH_ENDING=PARAM_FUTILITY_AT_PARENT_NODE_DEPTH_ENDING))
  #print('PARAM_FUTILITY_AT_PARENT_NODE_MARGIN1_OPENING     = {PARAM_FUTILITY_AT_PARENT_NODE_MARGIN1_OPENING}'.format(PARAM_FUTILITY_AT_PARENT_NODE_MARGIN1_OPENING=PARAM_FUTILITY_AT_PARENT_NODE_MARGIN1_OPENING))
  #print('PARAM_FUTILITY_AT_PARENT_NODE_MARGIN1_ENDING      = {PARAM_FUTILITY_AT_PARENT_NODE_MARGIN1_ENDING}'.format(PARAM_FUTILITY_AT_PARENT_NODE_MARGIN1_ENDING=PARAM_FUTILITY_AT_PARENT_NODE_MARGIN1_ENDING))
  #print('PARAM_FUTILITY_AT_PARENT_NODE_MARGIN2_OPENING     = {PARAM_FUTILITY_AT_PARENT_NODE_MARGIN2_OPENING}'.format(PARAM_FUTILITY_AT_PARENT_NODE_MARGIN2_OPENING=PARAM_FUTILITY_AT_PARENT_NODE_MARGIN2_OPENING))
  #print('PARAM_FUTILITY_AT_PARENT_NODE_MARGIN2_ENDING      = {PARAM_FUTILITY_AT_PARENT_NODE_MARGIN2_ENDING}'.format(PARAM_FUTILITY_AT_PARENT_NODE_MARGIN2_ENDING=PARAM_FUTILITY_AT_PARENT_NODE_MARGIN2_ENDING))
  #print('PARAM_FUTILITY_AT_PARENT_NODE_GAMMA1_OPENING      = {PARAM_FUTILITY_AT_PARENT_NODE_GAMMA1_OPENING}'.format(PARAM_FUTILITY_AT_PARENT_NODE_GAMMA1_OPENING=PARAM_FUTILITY_AT_PARENT_NODE_GAMMA1_OPENING))
  #print('PARAM_FUTILITY_AT_PARENT_NODE_GAMMA1_ENDING       = {PARAM_FUTILITY_AT_PARENT_NODE_GAMMA1_ENDING}'.format(PARAM_FUTILITY_AT_PARENT_NODE_GAMMA1_ENDING=PARAM_FUTILITY_AT_PARENT_NODE_GAMMA1_ENDING))
  #print('PARAM_FUTILITY_AT_PARENT_NODE_GAMMA2_OPENING      = {PARAM_FUTILITY_AT_PARENT_NODE_GAMMA2_OPENING}'.format(PARAM_FUTILITY_AT_PARENT_NODE_GAMMA2_OPENING=PARAM_FUTILITY_AT_PARENT_NODE_GAMMA2_OPENING))
  #print('PARAM_FUTILITY_AT_PARENT_NODE_GAMMA2_ENDING       = {PARAM_FUTILITY_AT_PARENT_NODE_GAMMA2_ENDING}'.format(PARAM_FUTILITY_AT_PARENT_NODE_GAMMA2_ENDING=PARAM_FUTILITY_AT_PARENT_NODE_GAMMA2_ENDING))
  #print('PARAM_NULL_MOVE_DYNAMIC_ALPHA_OPENING             = {PARAM_NULL_MOVE_DYNAMIC_ALPHA_OPENING}'.format(PARAM_NULL_MOVE_DYNAMIC_ALPHA_OPENING=PARAM_NULL_MOVE_DYNAMIC_ALPHA_OPENING))
  #print('PARAM_NULL_MOVE_DYNAMIC_ALPHA_ENDING              = {PARAM_NULL_MOVE_DYNAMIC_ALPHA_ENDING}'.format(PARAM_NULL_MOVE_DYNAMIC_ALPHA_ENDING=PARAM_NULL_MOVE_DYNAMIC_ALPHA_ENDING))
  #print('PARAM_NULL_MOVE_DYNAMIC_BETA_OPENING              = {PARAM_NULL_MOVE_DYNAMIC_BETA_OPENING}'.format(PARAM_NULL_MOVE_DYNAMIC_BETA_OPENING=PARAM_NULL_MOVE_DYNAMIC_BETA_OPENING))
  #print('PARAM_NULL_MOVE_DYNAMIC_BETA_ENDING               = {PARAM_NULL_MOVE_DYNAMIC_BETA_ENDING}'.format(PARAM_NULL_MOVE_DYNAMIC_BETA_ENDING=PARAM_NULL_MOVE_DYNAMIC_BETA_ENDING))
  #print('PARAM_NULL_MOVE_MARGIN_OPENING                    = {PARAM_NULL_MOVE_MARGIN_OPENING}'.format(PARAM_NULL_MOVE_MARGIN_OPENING=PARAM_NULL_MOVE_MARGIN_OPENING))
  #print('PARAM_NULL_MOVE_MARGIN_ENDING                     = {PARAM_NULL_MOVE_MARGIN_ENDING}'.format(PARAM_NULL_MOVE_MARGIN_ENDING=PARAM_NULL_MOVE_MARGIN_ENDING))
  #print('PARAM_NULL_MOVE_RETURN_DEPTH_OPENING              = {PARAM_NULL_MOVE_RETURN_DEPTH_OPENING}'.format(PARAM_NULL_MOVE_RETURN_DEPTH_OPENING=PARAM_NULL_MOVE_RETURN_DEPTH_OPENING))
  #print('PARAM_NULL_MOVE_RETURN_DEPTH_ENDING               = {PARAM_NULL_MOVE_RETURN_DEPTH_ENDING}'.format(PARAM_NULL_MOVE_RETURN_DEPTH_ENDING=PARAM_NULL_MOVE_RETURN_DEPTH_ENDING))
  #print('PARAM_PROBCUT_DEPTH_OPENING                       = {PARAM_PROBCUT_DEPTH_OPENING}'.format(PARAM_PROBCUT_DEPTH_OPENING=PARAM_PROBCUT_DEPTH_OPENING))
  #print('PARAM_PROBCUT_DEPTH_ENDING                        = {PARAM_PROBCUT_DEPTH_ENDING}'.format(PARAM_PROBCUT_DEPTH_ENDING=PARAM_PROBCUT_DEPTH_ENDING))
  #print('PARAM_PROBCUT_MARGIN_OPENING                      = {PARAM_PROBCUT_MARGIN_OPENING}'.format(PARAM_PROBCUT_MARGIN_OPENING=PARAM_PROBCUT_MARGIN_OPENING))
  #print('PARAM_PROBCUT_MARGIN_ENDING                       = {PARAM_PROBCUT_MARGIN_ENDING}'.format(PARAM_PROBCUT_MARGIN_ENDING=PARAM_PROBCUT_MARGIN_ENDING))
  #print('PARAM_SINGULAR_EXTENSION_DEPTH_OPENING            = {PARAM_SINGULAR_EXTENSION_DEPTH_OPENING}'.format(PARAM_SINGULAR_EXTENSION_DEPTH_OPENING=PARAM_SINGULAR_EXTENSION_DEPTH_OPENING))
  #print('PARAM_SINGULAR_EXTENSION_DEPTH_ENDING             = {PARAM_SINGULAR_EXTENSION_DEPTH_ENDING}'.format(PARAM_SINGULAR_EXTENSION_DEPTH_ENDING=PARAM_SINGULAR_EXTENSION_DEPTH_ENDING))
  #print('PARAM_SINGULAR_MARGIN_OPENING                     = {PARAM_SINGULAR_MARGIN_OPENING}'.format(PARAM_SINGULAR_MARGIN_OPENING=PARAM_SINGULAR_MARGIN_OPENING))
  #print('PARAM_SINGULAR_MARGIN_ENDING                      = {PARAM_SINGULAR_MARGIN_ENDING}'.format(PARAM_SINGULAR_MARGIN_ENDING=PARAM_SINGULAR_MARGIN_ENDING))
  #print('PARAM_SINGULAR_SEARCH_DEPTH_ALPHA_OPENING         = {PARAM_SINGULAR_SEARCH_DEPTH_ALPHA_OPENING}'.format(PARAM_SINGULAR_SEARCH_DEPTH_ALPHA_OPENING=PARAM_SINGULAR_SEARCH_DEPTH_ALPHA_OPENING))
  #print('PARAM_SINGULAR_SEARCH_DEPTH_ALPHA_ENDING          = {PARAM_SINGULAR_SEARCH_DEPTH_ALPHA_ENDING}'.format(PARAM_SINGULAR_SEARCH_DEPTH_ALPHA_ENDING=PARAM_SINGULAR_SEARCH_DEPTH_ALPHA_ENDING))
  #print('PARAM_PRUNING_BY_MOVE_COUNT_DEPTH_OPENING         = {PARAM_PRUNING_BY_MOVE_COUNT_DEPTH_OPENING}'.format(PARAM_PRUNING_BY_MOVE_COUNT_DEPTH_OPENING=PARAM_PRUNING_BY_MOVE_COUNT_DEPTH_OPENING))
  #print('PARAM_PRUNING_BY_MOVE_COUNT_DEPTH_ENDING          = {PARAM_PRUNING_BY_MOVE_COUNT_DEPTH_ENDING}'.format(PARAM_PRUNING_BY_MOVE_COUNT_DEPTH_ENDING=PARAM_PRUNING_BY_MOVE_COUNT_DEPTH_ENDING))
  #print('PARAM_PRUNING_BY_HISTORY_DEPTH_OPENING            = {PARAM_PRUNING_BY_HISTORY_DEPTH_OPENING}'.format(PARAM_PRUNING_BY_HISTORY_DEPTH_OPENING=PARAM_PRUNING_BY_HISTORY_DEPTH_OPENING))
  #print('PARAM_PRUNING_BY_HISTORY_DEPTH_ENDING             = {PARAM_PRUNING_BY_HISTORY_DEPTH_ENDING}'.format(PARAM_PRUNING_BY_HISTORY_DEPTH_ENDING=PARAM_PRUNING_BY_HISTORY_DEPTH_ENDING))
  #print('PARAM_REDUCTION_BY_HISTORY_OPENING                = {PARAM_REDUCTION_BY_HISTORY_OPENING}'.format(PARAM_REDUCTION_BY_HISTORY_OPENING=PARAM_REDUCTION_BY_HISTORY_OPENING))
  #print('PARAM_REDUCTION_BY_HISTORY_ENDING                 = {PARAM_REDUCTION_BY_HISTORY_ENDING}'.format(PARAM_REDUCTION_BY_HISTORY_ENDING=PARAM_REDUCTION_BY_HISTORY_ENDING))
  #print('PARAM_IID_MARGIN_ALPHA_OPENING                    = {PARAM_IID_MARGIN_ALPHA_OPENING}'.format(PARAM_IID_MARGIN_ALPHA_OPENING=PARAM_IID_MARGIN_ALPHA_OPENING))
  #print('PARAM_IID_MARGIN_ALPHA_ENDING                     = {PARAM_IID_MARGIN_ALPHA_ENDING}'.format(PARAM_IID_MARGIN_ALPHA_ENDING=PARAM_IID_MARGIN_ALPHA_ENDING))
  #print('PARAM_RAZORING_MARGIN1_OPENING                    = {PARAM_RAZORING_MARGIN1_OPENING}'.format(PARAM_RAZORING_MARGIN1_OPENING=PARAM_RAZORING_MARGIN1_OPENING))
  #print('PARAM_RAZORING_MARGIN1_ENDING                     = {PARAM_RAZORING_MARGIN1_ENDING}'.format(PARAM_RAZORING_MARGIN1_ENDING=PARAM_RAZORING_MARGIN1_ENDING))
  #print('PARAM_RAZORING_MARGIN2_OPENING                    = {PARAM_RAZORING_MARGIN2_OPENING}'.format(PARAM_RAZORING_MARGIN2_OPENING=PARAM_RAZORING_MARGIN2_OPENING))
  #print('PARAM_RAZORING_MARGIN2_ENDING                     = {PARAM_RAZORING_MARGIN2_ENDING}'.format(PARAM_RAZORING_MARGIN2_ENDING=PARAM_RAZORING_MARGIN2_ENDING))
  #print('PARAM_RAZORING_MARGIN3_OPENING                    = {PARAM_RAZORING_MARGIN3_OPENING}'.format(PARAM_RAZORING_MARGIN3_OPENING=PARAM_RAZORING_MARGIN3_OPENING))
  #print('PARAM_RAZORING_MARGIN3_ENDING                     = {PARAM_RAZORING_MARGIN3_ENDING}'.format(PARAM_RAZORING_MARGIN3_ENDING=PARAM_RAZORING_MARGIN3_ENDING))
  #print('PARAM_RAZORING_MARGIN4_OPENING                    = {PARAM_RAZORING_MARGIN4_OPENING}'.format(PARAM_RAZORING_MARGIN4_OPENING=PARAM_RAZORING_MARGIN4_OPENING))
  #print('PARAM_RAZORING_MARGIN4_ENDING                     = {PARAM_RAZORING_MARGIN4_ENDING}'.format(PARAM_RAZORING_MARGIN4_ENDING=PARAM_RAZORING_MARGIN4_ENDING))
  #print('PARAM_REDUCTION_ALPHA_OPENING                     = {PARAM_REDUCTION_ALPHA_OPENING}'.format(PARAM_REDUCTION_ALPHA_OPENING=PARAM_REDUCTION_ALPHA_OPENING))
  #print('PARAM_REDUCTION_ALPHA_ENDING                      = {PARAM_REDUCTION_ALPHA_ENDING}'.format(PARAM_REDUCTION_ALPHA_ENDING=PARAM_REDUCTION_ALPHA_ENDING))
  #print('PARAM_FUTILITY_MOVE_COUNT_ALPHA0_OPENING          = {PARAM_FUTILITY_MOVE_COUNT_ALPHA0_OPENING}'.format(PARAM_FUTILITY_MOVE_COUNT_ALPHA0_OPENING=PARAM_FUTILITY_MOVE_COUNT_ALPHA0_OPENING))
  #print('PARAM_FUTILITY_MOVE_COUNT_ALPHA0_ENDING           = {PARAM_FUTILITY_MOVE_COUNT_ALPHA0_ENDING}'.format(PARAM_FUTILITY_MOVE_COUNT_ALPHA0_ENDING=PARAM_FUTILITY_MOVE_COUNT_ALPHA0_ENDING))
  #print('PARAM_FUTILITY_MOVE_COUNT_ALPHA1_OPENING          = {PARAM_FUTILITY_MOVE_COUNT_ALPHA1_OPENING}'.format(PARAM_FUTILITY_MOVE_COUNT_ALPHA1_OPENING=PARAM_FUTILITY_MOVE_COUNT_ALPHA1_OPENING))
  #print('PARAM_FUTILITY_MOVE_COUNT_ALPHA1_ENDING           = {PARAM_FUTILITY_MOVE_COUNT_ALPHA1_ENDING}'.format(PARAM_FUTILITY_MOVE_COUNT_ALPHA1_ENDING=PARAM_FUTILITY_MOVE_COUNT_ALPHA1_ENDING))
  #print('PARAM_FUTILITY_MOVE_COUNT_BETA0_OPENING           = {PARAM_FUTILITY_MOVE_COUNT_BETA0_OPENING}'.format(PARAM_FUTILITY_MOVE_COUNT_BETA0_OPENING=PARAM_FUTILITY_MOVE_COUNT_BETA0_OPENING))
  #print('PARAM_FUTILITY_MOVE_COUNT_BETA0_ENDING            = {PARAM_FUTILITY_MOVE_COUNT_BETA0_ENDING}'.format(PARAM_FUTILITY_MOVE_COUNT_BETA0_ENDING=PARAM_FUTILITY_MOVE_COUNT_BETA0_ENDING))
  #print('PARAM_FUTILITY_MOVE_COUNT_BETA1_OPENING           = {PARAM_FUTILITY_MOVE_COUNT_BETA1_OPENING}'.format(PARAM_FUTILITY_MOVE_COUNT_BETA1_OPENING=PARAM_FUTILITY_MOVE_COUNT_BETA1_OPENING))
  #print('PARAM_FUTILITY_MOVE_COUNT_BETA1_ENDING            = {PARAM_FUTILITY_MOVE_COUNT_BETA1_ENDING}'.format(PARAM_FUTILITY_MOVE_COUNT_BETA1_ENDING=PARAM_FUTILITY_MOVE_COUNT_BETA1_ENDING))
  #print('PARAM_QUIET_SEARCH_COUNT_OPENING                  = {PARAM_QUIET_SEARCH_COUNT_OPENING}'.format(PARAM_QUIET_SEARCH_COUNT_OPENING=PARAM_QUIET_SEARCH_COUNT_OPENING))
  #print('PARAM_QUIET_SEARCH_COUNT_ENDING                   = {PARAM_QUIET_SEARCH_COUNT_ENDING}'.format(PARAM_QUIET_SEARCH_COUNT_ENDING=PARAM_QUIET_SEARCH_COUNT_ENDING))
  #print('PARAM_QSEARCH_MATE1_OPENING                       = {PARAM_QSEARCH_MATE1_OPENING}'.format(PARAM_QSEARCH_MATE1_OPENING=PARAM_QSEARCH_MATE1_OPENING))
  #print('PARAM_QSEARCH_MATE1_ENDING                        = {PARAM_QSEARCH_MATE1_ENDING}'.format(PARAM_QSEARCH_MATE1_ENDING=PARAM_QSEARCH_MATE1_ENDING))
  #print('PARAM_SEARCH_MATE1_OPENING                        = {PARAM_SEARCH_MATE1_OPENING}'.format(PARAM_SEARCH_MATE1_OPENING=PARAM_SEARCH_MATE1_OPENING))
  #print('PARAM_SEARCH_MATE1_ENDING                         = {PARAM_SEARCH_MATE1_ENDING}'.format(PARAM_SEARCH_MATE1_ENDING=PARAM_SEARCH_MATE1_ENDING))
  #print('PARAM_WEAK_MATE_PLY_OPENING                       = {PARAM_WEAK_MATE_PLY_OPENING}'.format(PARAM_WEAK_MATE_PLY_OPENING=PARAM_WEAK_MATE_PLY_OPENING))
  #print('PARAM_WEAK_MATE_PLY_ENDING                        = {PARAM_WEAK_MATE_PLY_ENDING}'.format(PARAM_WEAK_MATE_PLY_ENDING=PARAM_WEAK_MATE_PLY_ENDING))

  if START_COUNTER < CURRENT_COUNTER:
    current_time_sec = time.time()
    delta = current_time_sec - START_TIME_SEC
    sec_per_one = delta / (CURRENT_COUNTER - START_COUNTER)
    remaining = datetime.timedelta(seconds=sec_per_one*(MAX_EVALS-CURRENT_COUNTER))
    print(CURRENT_COUNTER, '/', MAX_EVALS, str(remaining))
    sys.stdout.flush()
  CURRENT_COUNTER += 1

  WriteHeaderFile(
    PARAM_FUTILITY_MARGIN_ALPHA_OPENING,
    PARAM_FUTILITY_MARGIN_ALPHA_ENDING,
    PARAM_FUTILITY_MARGIN_BETA_OPENING,
    PARAM_FUTILITY_MARGIN_BETA_ENDING,
    PARAM_FUTILITY_MARGIN_QUIET_OPENING,
    PARAM_FUTILITY_MARGIN_QUIET_ENDING,
    PARAM_FUTILITY_RETURN_DEPTH_OPENING,
    PARAM_FUTILITY_RETURN_DEPTH_ENDING,
    PARAM_FUTILITY_AT_PARENT_NODE_DEPTH_OPENING,
    PARAM_FUTILITY_AT_PARENT_NODE_DEPTH_ENDING,
    PARAM_FUTILITY_AT_PARENT_NODE_MARGIN1_OPENING,
    PARAM_FUTILITY_AT_PARENT_NODE_MARGIN1_ENDING,
    PARAM_FUTILITY_AT_PARENT_NODE_MARGIN2_OPENING,
    PARAM_FUTILITY_AT_PARENT_NODE_MARGIN2_ENDING,
    PARAM_FUTILITY_AT_PARENT_NODE_GAMMA1_OPENING,
    PARAM_FUTILITY_AT_PARENT_NODE_GAMMA1_ENDING,
    PARAM_FUTILITY_AT_PARENT_NODE_GAMMA2_OPENING,
    PARAM_FUTILITY_AT_PARENT_NODE_GAMMA2_ENDING,
    PARAM_NULL_MOVE_DYNAMIC_ALPHA_OPENING,
    PARAM_NULL_MOVE_DYNAMIC_ALPHA_ENDING,
    PARAM_NULL_MOVE_DYNAMIC_BETA_OPENING,
    PARAM_NULL_MOVE_DYNAMIC_BETA_ENDING,
    PARAM_NULL_MOVE_MARGIN_OPENING,
    PARAM_NULL_MOVE_MARGIN_ENDING,
    PARAM_NULL_MOVE_RETURN_DEPTH_OPENING,
    PARAM_NULL_MOVE_RETURN_DEPTH_ENDING,
    PARAM_PROBCUT_DEPTH_OPENING,
    PARAM_PROBCUT_DEPTH_ENDING,
    PARAM_PROBCUT_MARGIN_OPENING,
    PARAM_PROBCUT_MARGIN_ENDING,
    PARAM_SINGULAR_EXTENSION_DEPTH_OPENING,
    PARAM_SINGULAR_EXTENSION_DEPTH_ENDING,
    PARAM_SINGULAR_MARGIN_OPENING,
    PARAM_SINGULAR_MARGIN_ENDING,
    PARAM_SINGULAR_SEARCH_DEPTH_ALPHA_OPENING,
    PARAM_SINGULAR_SEARCH_DEPTH_ALPHA_ENDING,
    PARAM_PRUNING_BY_MOVE_COUNT_DEPTH_OPENING,
    PARAM_PRUNING_BY_MOVE_COUNT_DEPTH_ENDING,
    PARAM_PRUNING_BY_HISTORY_DEPTH_OPENING,
    PARAM_PRUNING_BY_HISTORY_DEPTH_ENDING,
    PARAM_REDUCTION_BY_HISTORY_OPENING,
    PARAM_REDUCTION_BY_HISTORY_ENDING,
    PARAM_IID_MARGIN_ALPHA_OPENING,
    PARAM_IID_MARGIN_ALPHA_ENDING,
    PARAM_RAZORING_MARGIN1_OPENING,
    PARAM_RAZORING_MARGIN1_ENDING,
    PARAM_RAZORING_MARGIN2_OPENING,
    PARAM_RAZORING_MARGIN2_ENDING,
    PARAM_RAZORING_MARGIN3_OPENING,
    PARAM_RAZORING_MARGIN3_ENDING,
    PARAM_RAZORING_MARGIN4_OPENING,
    PARAM_RAZORING_MARGIN4_ENDING,
    PARAM_REDUCTION_ALPHA_OPENING,
    PARAM_REDUCTION_ALPHA_ENDING,
    PARAM_FUTILITY_MOVE_COUNT_ALPHA0_OPENING,
    PARAM_FUTILITY_MOVE_COUNT_ALPHA0_ENDING,
    PARAM_FUTILITY_MOVE_COUNT_ALPHA1_OPENING,
    PARAM_FUTILITY_MOVE_COUNT_ALPHA1_ENDING,
    PARAM_FUTILITY_MOVE_COUNT_BETA0_OPENING,
    PARAM_FUTILITY_MOVE_COUNT_BETA0_ENDING,
    PARAM_FUTILITY_MOVE_COUNT_BETA1_OPENING,
    PARAM_FUTILITY_MOVE_COUNT_BETA1_ENDING,
    PARAM_QUIET_SEARCH_COUNT_OPENING,
    PARAM_QUIET_SEARCH_COUNT_ENDING,
    PARAM_QSEARCH_MATE1_OPENING,
    PARAM_QSEARCH_MATE1_ENDING,
    PARAM_SEARCH_MATE1_OPENING,
    PARAM_SEARCH_MATE1_ENDING,
    PARAM_WEAK_MATE_PLY_OPENING,
    PARAM_WEAK_MATE_PLY_ENDING)

  engine_invoker_args = [
    'C:\\Python27\\python.exe',
    '..\script\engine_invoker5.py',
    # hakubishin-private\exe以下から実行していると仮定する
    'home:{0}'.format(os.getcwd()),
    # {home}\exeからの相対パスに変換する
    'engine1:{0}'.format(os.path.relpath(os.path.abspath(ENGINE1), os.path.join(os.getcwd(), 'exe'))),
    # {home}\evalからの相対パスに変換する
    'eval1:{0}'.format(os.path.relpath(os.path.abspath(EVAL_DIR), os.path.join(os.getcwd(), 'eval'))),
    'engine2:{0}'.format(os.path.relpath(os.path.abspath(ENGINE2), os.path.join(os.getcwd(), 'exe'))),
    'eval2:{0}'.format(os.path.relpath(os.path.abspath(EVAL_DIR), os.path.join(os.getcwd(), 'eval'))),
    'cores:{0}'.format(NUM_THREADS),
    'loop:{0}'.format(NUM_THREADS),
    'cpu:{0}'.format(NUM_NUMA_NODES),
    'engine_threads:1',
    'hash1:{0}'.format(HASH),
    'hash2:{0}'.format(HASH),
    'time:b{0}'.format(THINKING_TIME_MS),
    'rand_book:1'
    ]
  print(engine_invoker_args)
  sys.stdout.flush()

  completed_process = subprocess.run(engine_invoker_args, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True)

  if completed_process.stdout:
    print('-' * 78)
    print('- stdout')
    print('-' * 78)
    print('')
    print(completed_process.stdout)
    print('')
  if completed_process.stderr:
    print('-' * 78)
    print('- sterr')
    print('-' * 78)
    print('')
    print(completed_process.stderr)
    print('')
  sys.stdout.flush()

  if completed_process.returncode:
    sys.exit('Failed to execute engine_invoker...')

  win = 0
  draw = 0
  lose = 0
  for match in re.compile(',(\\d+) - (\\d+) - (\\d+)\\(').finditer(completed_process.stdout):
    win = float(match.group(1))
    draw = float(match.group(2))
    lose = float(match.group(3))

  ratio = 0.0
  if win + draw + lose > 0.1:
   ratio = win / (win + draw + lose)
  print('ratio={0}'.format(ratio))
  sys.stdout.flush()

  global STATE
  STATE['PARAM_FUTILITY_MARGIN_ALPHA_OPENING'].append(PARAM_FUTILITY_MARGIN_ALPHA_OPENING)
  STATE['PARAM_FUTILITY_MARGIN_ALPHA_ENDING'].append(PARAM_FUTILITY_MARGIN_ALPHA_ENDING)
  STATE['PARAM_FUTILITY_MARGIN_BETA_OPENING'].append(PARAM_FUTILITY_MARGIN_BETA_OPENING)
  STATE['PARAM_FUTILITY_MARGIN_BETA_ENDING'].append(PARAM_FUTILITY_MARGIN_BETA_ENDING)
  STATE['PARAM_FUTILITY_MARGIN_QUIET_OPENING'].append(PARAM_FUTILITY_MARGIN_QUIET_OPENING)
  STATE['PARAM_FUTILITY_MARGIN_QUIET_ENDING'].append(PARAM_FUTILITY_MARGIN_QUIET_ENDING)
  STATE['PARAM_FUTILITY_RETURN_DEPTH_OPENING'].append(PARAM_FUTILITY_RETURN_DEPTH_OPENING)
  STATE['PARAM_FUTILITY_RETURN_DEPTH_ENDING'].append(PARAM_FUTILITY_RETURN_DEPTH_ENDING)
  STATE['PARAM_FUTILITY_AT_PARENT_NODE_DEPTH_OPENING'].append(PARAM_FUTILITY_AT_PARENT_NODE_DEPTH_OPENING)
  STATE['PARAM_FUTILITY_AT_PARENT_NODE_DEPTH_ENDING'].append(PARAM_FUTILITY_AT_PARENT_NODE_DEPTH_ENDING)
  STATE['PARAM_FUTILITY_AT_PARENT_NODE_MARGIN1_OPENING'].append(PARAM_FUTILITY_AT_PARENT_NODE_MARGIN1_OPENING)
  STATE['PARAM_FUTILITY_AT_PARENT_NODE_MARGIN1_ENDING'].append(PARAM_FUTILITY_AT_PARENT_NODE_MARGIN1_ENDING)
  STATE['PARAM_FUTILITY_AT_PARENT_NODE_MARGIN2_OPENING'].append(PARAM_FUTILITY_AT_PARENT_NODE_MARGIN2_OPENING)
  STATE['PARAM_FUTILITY_AT_PARENT_NODE_MARGIN2_ENDING'].append(PARAM_FUTILITY_AT_PARENT_NODE_MARGIN2_ENDING)
  STATE['PARAM_FUTILITY_AT_PARENT_NODE_GAMMA1_OPENING'].append(PARAM_FUTILITY_AT_PARENT_NODE_GAMMA1_OPENING)
  STATE['PARAM_FUTILITY_AT_PARENT_NODE_GAMMA1_ENDING'].append(PARAM_FUTILITY_AT_PARENT_NODE_GAMMA1_ENDING)
  STATE['PARAM_FUTILITY_AT_PARENT_NODE_GAMMA2_OPENING'].append(PARAM_FUTILITY_AT_PARENT_NODE_GAMMA2_OPENING)
  STATE['PARAM_FUTILITY_AT_PARENT_NODE_GAMMA2_ENDING'].append(PARAM_FUTILITY_AT_PARENT_NODE_GAMMA2_ENDING)
  STATE['PARAM_NULL_MOVE_DYNAMIC_ALPHA_OPENING'].append(PARAM_NULL_MOVE_DYNAMIC_ALPHA_OPENING)
  STATE['PARAM_NULL_MOVE_DYNAMIC_ALPHA_ENDING'].append(PARAM_NULL_MOVE_DYNAMIC_ALPHA_ENDING)
  STATE['PARAM_NULL_MOVE_DYNAMIC_BETA_OPENING'].append(PARAM_NULL_MOVE_DYNAMIC_BETA_OPENING)
  STATE['PARAM_NULL_MOVE_DYNAMIC_BETA_ENDING'].append(PARAM_NULL_MOVE_DYNAMIC_BETA_ENDING)
  STATE['PARAM_NULL_MOVE_MARGIN_OPENING'].append(PARAM_NULL_MOVE_MARGIN_OPENING)
  STATE['PARAM_NULL_MOVE_MARGIN_ENDING'].append(PARAM_NULL_MOVE_MARGIN_ENDING)
  STATE['PARAM_NULL_MOVE_RETURN_DEPTH_OPENING'].append(PARAM_NULL_MOVE_RETURN_DEPTH_OPENING)
  STATE['PARAM_NULL_MOVE_RETURN_DEPTH_ENDING'].append(PARAM_NULL_MOVE_RETURN_DEPTH_ENDING)
  STATE['PARAM_PROBCUT_DEPTH_OPENING'].append(PARAM_PROBCUT_DEPTH_OPENING)
  STATE['PARAM_PROBCUT_DEPTH_ENDING'].append(PARAM_PROBCUT_DEPTH_ENDING)
  STATE['PARAM_PROBCUT_MARGIN_OPENING'].append(PARAM_PROBCUT_MARGIN_OPENING)
  STATE['PARAM_PROBCUT_MARGIN_ENDING'].append(PARAM_PROBCUT_MARGIN_ENDING)
  STATE['PARAM_SINGULAR_EXTENSION_DEPTH_OPENING'].append(PARAM_SINGULAR_EXTENSION_DEPTH_OPENING)
  STATE['PARAM_SINGULAR_EXTENSION_DEPTH_ENDING'].append(PARAM_SINGULAR_EXTENSION_DEPTH_ENDING)
  STATE['PARAM_SINGULAR_MARGIN_OPENING'].append(PARAM_SINGULAR_MARGIN_OPENING)
  STATE['PARAM_SINGULAR_MARGIN_ENDING'].append(PARAM_SINGULAR_MARGIN_ENDING)
  STATE['PARAM_SINGULAR_SEARCH_DEPTH_ALPHA_OPENING'].append(PARAM_SINGULAR_SEARCH_DEPTH_ALPHA_OPENING)
  STATE['PARAM_SINGULAR_SEARCH_DEPTH_ALPHA_ENDING'].append(PARAM_SINGULAR_SEARCH_DEPTH_ALPHA_ENDING)
  STATE['PARAM_PRUNING_BY_MOVE_COUNT_DEPTH_OPENING'].append(PARAM_PRUNING_BY_MOVE_COUNT_DEPTH_OPENING)
  STATE['PARAM_PRUNING_BY_MOVE_COUNT_DEPTH_ENDING'].append(PARAM_PRUNING_BY_MOVE_COUNT_DEPTH_ENDING)
  STATE['PARAM_PRUNING_BY_HISTORY_DEPTH_OPENING'].append(PARAM_PRUNING_BY_HISTORY_DEPTH_OPENING)
  STATE['PARAM_PRUNING_BY_HISTORY_DEPTH_ENDING'].append(PARAM_PRUNING_BY_HISTORY_DEPTH_ENDING)
  STATE['PARAM_REDUCTION_BY_HISTORY_OPENING'].append(PARAM_REDUCTION_BY_HISTORY_OPENING)
  STATE['PARAM_REDUCTION_BY_HISTORY_ENDING'].append(PARAM_REDUCTION_BY_HISTORY_ENDING)
  STATE['PARAM_IID_MARGIN_ALPHA_OPENING'].append(PARAM_IID_MARGIN_ALPHA_OPENING)
  STATE['PARAM_IID_MARGIN_ALPHA_ENDING'].append(PARAM_IID_MARGIN_ALPHA_ENDING)
  STATE['PARAM_RAZORING_MARGIN1_OPENING'].append(PARAM_RAZORING_MARGIN1_OPENING)
  STATE['PARAM_RAZORING_MARGIN1_ENDING'].append(PARAM_RAZORING_MARGIN1_ENDING)
  STATE['PARAM_RAZORING_MARGIN2_OPENING'].append(PARAM_RAZORING_MARGIN2_OPENING)
  STATE['PARAM_RAZORING_MARGIN2_ENDING'].append(PARAM_RAZORING_MARGIN2_ENDING)
  STATE['PARAM_RAZORING_MARGIN3_OPENING'].append(PARAM_RAZORING_MARGIN3_OPENING)
  STATE['PARAM_RAZORING_MARGIN3_ENDING'].append(PARAM_RAZORING_MARGIN3_ENDING)
  STATE['PARAM_RAZORING_MARGIN4_OPENING'].append(PARAM_RAZORING_MARGIN4_OPENING)
  STATE['PARAM_RAZORING_MARGIN4_ENDING'].append(PARAM_RAZORING_MARGIN4_ENDING)
  STATE['PARAM_REDUCTION_ALPHA_OPENING'].append(PARAM_REDUCTION_ALPHA_OPENING)
  STATE['PARAM_REDUCTION_ALPHA_ENDING'].append(PARAM_REDUCTION_ALPHA_ENDING)
  STATE['PARAM_FUTILITY_MOVE_COUNT_ALPHA0_OPENING'].append(PARAM_FUTILITY_MOVE_COUNT_ALPHA0_OPENING)
  STATE['PARAM_FUTILITY_MOVE_COUNT_ALPHA0_ENDING'].append(PARAM_FUTILITY_MOVE_COUNT_ALPHA0_ENDING)
  STATE['PARAM_FUTILITY_MOVE_COUNT_ALPHA1_OPENING'].append(PARAM_FUTILITY_MOVE_COUNT_ALPHA1_OPENING)
  STATE['PARAM_FUTILITY_MOVE_COUNT_ALPHA1_ENDING'].append(PARAM_FUTILITY_MOVE_COUNT_ALPHA1_ENDING)
  STATE['PARAM_FUTILITY_MOVE_COUNT_BETA0_OPENING'].append(PARAM_FUTILITY_MOVE_COUNT_BETA0_OPENING)
  STATE['PARAM_FUTILITY_MOVE_COUNT_BETA0_ENDING'].append(PARAM_FUTILITY_MOVE_COUNT_BETA0_ENDING)
  STATE['PARAM_FUTILITY_MOVE_COUNT_BETA1_OPENING'].append(PARAM_FUTILITY_MOVE_COUNT_BETA1_OPENING)
  STATE['PARAM_FUTILITY_MOVE_COUNT_BETA1_ENDING'].append(PARAM_FUTILITY_MOVE_COUNT_BETA1_ENDING)
  STATE['PARAM_QUIET_SEARCH_COUNT_OPENING'].append(PARAM_QUIET_SEARCH_COUNT_OPENING)
  STATE['PARAM_QUIET_SEARCH_COUNT_ENDING'].append(PARAM_QUIET_SEARCH_COUNT_ENDING)
  STATE['PARAM_QSEARCH_MATE1_OPENING'].append(PARAM_QSEARCH_MATE1_OPENING)
  STATE['PARAM_QSEARCH_MATE1_ENDING'].append(PARAM_QSEARCH_MATE1_ENDING)
  STATE['PARAM_SEARCH_MATE1_OPENING'].append(PARAM_SEARCH_MATE1_OPENING)
  STATE['PARAM_SEARCH_MATE1_ENDING'].append(PARAM_SEARCH_MATE1_ENDING)
  STATE['PARAM_WEAK_MATE_PLY_OPENING'].append(PARAM_WEAK_MATE_PLY_OPENING)
  STATE['PARAM_WEAK_MATE_PLY_ENDING'].append(PARAM_WEAK_MATE_PLY_ENDING)
  STATE['target'].append(ratio)

  try:
    with open(STATE_FILE_NAME, 'wb') as fo:
      pickle.dump(STATE, fo, protocol=-1)
      print('saved state to: {}'.format(STATE_FILE_NAME))
  except Exception as e:
    sys.exit('Failed to save state. exitting... e={}'.format(e))

  return ratio


def main():
  global CURRENT_COUNTER
  global HASH
  global MAX_EVALS
  global NUM_NUMA_NODES
  global NUM_THREADS
  global START_COUNTER
  global STATE
  global STATE_FILE_NAME
  global THINKING_TIME_MS

  parser = argparse.ArgumentParser(description='Tanuki Optimizer 2')
  parser.add_argument('--resume', action='store_true',
      help=u'resume hyper-parameter search from a file.')
  parser.add_argument('--max_evals', type=int, default=MAX_EVALS,
      help=u'max evaluation for Bayesian Optimization. (default: use MAX_EVALS={})'.format(MAX_EVALS))
  parser.add_argument('--num_threads', type=int, default=NUM_THREADS,
      help=u'number of threads. (default: use NUM_THREADS={})'.format(NUM_THREADS))
  parser.add_argument('--thinking_time_ms', type=int, default=THINKING_TIME_MS,
      help=u'thinking time. (default: use THINKING_TIME_MS={})'.format(THINKING_TIME_MS))
  parser.add_argument('--num_numa_nodes', type=int, default=NUM_NUMA_NODES,
      help=u'Number of the NUMA nodes. (default: use NUM_NUMA_NODES={})'.format(NUM_NUMA_NODES))
  parser.add_argument('--hash', type=int, default=HASH,
      help=u'Transposition table hash size. (default: use HASH={})'.format(HASH))
  commandline_args = parser.parse_args()
  MAX_EVALS = commandline_args.max_evals
  NUM_THREADS = commandline_args.num_threads
  THINKING_TIME_MS = commandline_args.thinking_time_ms
  NUM_NUMA_NODES = commandline_args.num_numa_nodes
  HASH = commandline_args.hash

  if commandline_args.resume:
    with open(STATE_FILE_NAME, 'rb') as fi:
      STATE = pickle.load(fi)
      START_COUNTER = len(STATE['target'])
      CURRENT_COUNTER = START_COUNTER
      print('resume from state: {} ({} iteration done)'.format(STATE_FILE_NAME, len(STATE['target'])))

  bo = bayes_opt.BayesianOptimization(Function, {
    'PARAM_FUTILITY_MARGIN_ALPHA_OPENING': [0.0, 1.0],
    'PARAM_FUTILITY_MARGIN_ALPHA_ENDING': [0.0, 1.0],
    'PARAM_FUTILITY_MARGIN_BETA_OPENING': [0.0, 1.0],
    'PARAM_FUTILITY_MARGIN_BETA_ENDING': [0.0, 1.0],
    'PARAM_FUTILITY_MARGIN_QUIET_OPENING': [0.0, 1.0],
    'PARAM_FUTILITY_MARGIN_QUIET_ENDING': [0.0, 1.0],
    'PARAM_FUTILITY_RETURN_DEPTH_OPENING': [0.0, 1.0],
    'PARAM_FUTILITY_RETURN_DEPTH_ENDING': [0.0, 1.0],
    'PARAM_FUTILITY_AT_PARENT_NODE_DEPTH_OPENING': [0.0, 1.0],
    'PARAM_FUTILITY_AT_PARENT_NODE_DEPTH_ENDING': [0.0, 1.0],
    'PARAM_FUTILITY_AT_PARENT_NODE_MARGIN1_OPENING': [0.0, 1.0],
    'PARAM_FUTILITY_AT_PARENT_NODE_MARGIN1_ENDING': [0.0, 1.0],
    'PARAM_FUTILITY_AT_PARENT_NODE_MARGIN2_OPENING': [0.0, 1.0],
    'PARAM_FUTILITY_AT_PARENT_NODE_MARGIN2_ENDING': [0.0, 1.0],
    'PARAM_FUTILITY_AT_PARENT_NODE_GAMMA1_OPENING': [0.0, 1.0],
    'PARAM_FUTILITY_AT_PARENT_NODE_GAMMA1_ENDING': [0.0, 1.0],
    'PARAM_FUTILITY_AT_PARENT_NODE_GAMMA2_OPENING': [0.0, 1.0],
    'PARAM_FUTILITY_AT_PARENT_NODE_GAMMA2_ENDING': [0.0, 1.0],
    'PARAM_NULL_MOVE_DYNAMIC_ALPHA_OPENING': [0.0, 1.0],
    'PARAM_NULL_MOVE_DYNAMIC_ALPHA_ENDING': [0.0, 1.0],
    'PARAM_NULL_MOVE_DYNAMIC_BETA_OPENING': [0.0, 1.0],
    'PARAM_NULL_MOVE_DYNAMIC_BETA_ENDING': [0.0, 1.0],
    'PARAM_NULL_MOVE_MARGIN_OPENING': [0.0, 1.0],
    'PARAM_NULL_MOVE_MARGIN_ENDING': [0.0, 1.0],
    'PARAM_NULL_MOVE_RETURN_DEPTH_OPENING': [0.0, 1.0],
    'PARAM_NULL_MOVE_RETURN_DEPTH_ENDING': [0.0, 1.0],
    'PARAM_PROBCUT_DEPTH_OPENING': [0.0, 1.0],
    'PARAM_PROBCUT_DEPTH_ENDING': [0.0, 1.0],
    'PARAM_PROBCUT_MARGIN_OPENING': [0.0, 1.0],
    'PARAM_PROBCUT_MARGIN_ENDING': [0.0, 1.0],
    'PARAM_SINGULAR_EXTENSION_DEPTH_OPENING': [0.0, 1.0],
    'PARAM_SINGULAR_EXTENSION_DEPTH_ENDING': [0.0, 1.0],
    'PARAM_SINGULAR_MARGIN_OPENING': [0.0, 1.0],
    'PARAM_SINGULAR_MARGIN_ENDING': [0.0, 1.0],
    'PARAM_SINGULAR_SEARCH_DEPTH_ALPHA_OPENING': [0.0, 1.0],
    'PARAM_SINGULAR_SEARCH_DEPTH_ALPHA_ENDING': [0.0, 1.0],
    'PARAM_PRUNING_BY_MOVE_COUNT_DEPTH_OPENING': [0.0, 1.0],
    'PARAM_PRUNING_BY_MOVE_COUNT_DEPTH_ENDING': [0.0, 1.0],
    'PARAM_PRUNING_BY_HISTORY_DEPTH_OPENING': [0.0, 1.0],
    'PARAM_PRUNING_BY_HISTORY_DEPTH_ENDING': [0.0, 1.0],
    'PARAM_REDUCTION_BY_HISTORY_OPENING': [0.0, 1.0],
    'PARAM_REDUCTION_BY_HISTORY_ENDING': [0.0, 1.0],
    'PARAM_IID_MARGIN_ALPHA_OPENING': [0.0, 1.0],
    'PARAM_IID_MARGIN_ALPHA_ENDING': [0.0, 1.0],
    'PARAM_RAZORING_MARGIN1_OPENING': [0.0, 1.0],
    'PARAM_RAZORING_MARGIN1_ENDING': [0.0, 1.0],
    'PARAM_RAZORING_MARGIN2_OPENING': [0.0, 1.0],
    'PARAM_RAZORING_MARGIN2_ENDING': [0.0, 1.0],
    'PARAM_RAZORING_MARGIN3_OPENING': [0.0, 1.0],
    'PARAM_RAZORING_MARGIN3_ENDING': [0.0, 1.0],
    'PARAM_RAZORING_MARGIN4_OPENING': [0.0, 1.0],
    'PARAM_RAZORING_MARGIN4_ENDING': [0.0, 1.0],
    'PARAM_REDUCTION_ALPHA_OPENING': [0.0, 1.0],
    'PARAM_REDUCTION_ALPHA_ENDING': [0.0, 1.0],
    'PARAM_FUTILITY_MOVE_COUNT_ALPHA0_OPENING': [0.0, 1.0],
    'PARAM_FUTILITY_MOVE_COUNT_ALPHA0_ENDING': [0.0, 1.0],
    'PARAM_FUTILITY_MOVE_COUNT_ALPHA1_OPENING': [0.0, 1.0],
    'PARAM_FUTILITY_MOVE_COUNT_ALPHA1_ENDING': [0.0, 1.0],
    'PARAM_FUTILITY_MOVE_COUNT_BETA0_OPENING': [0.0, 1.0],
    'PARAM_FUTILITY_MOVE_COUNT_BETA0_ENDING': [0.0, 1.0],
    'PARAM_FUTILITY_MOVE_COUNT_BETA1_OPENING': [0.0, 1.0],
    'PARAM_FUTILITY_MOVE_COUNT_BETA1_ENDING': [0.0, 1.0],
    'PARAM_QUIET_SEARCH_COUNT_OPENING': [0.0, 1.0],
    'PARAM_QUIET_SEARCH_COUNT_ENDING': [0.0, 1.0],
    'PARAM_QSEARCH_MATE1_OPENING': [0.0, 1.0],
    'PARAM_QSEARCH_MATE1_ENDING': [0.0, 1.0],
    'PARAM_SEARCH_MATE1_OPENING': [0.0, 1.0],
    'PARAM_SEARCH_MATE1_ENDING': [0.0, 1.0],
    'PARAM_WEAK_MATE_PLY_OPENING': [0.0, 1.0],
    'PARAM_WEAK_MATE_PLY_ENDING': [0.0, 1.0],
    })
  bo.initialize(STATE)
  remaining = MAX_EVALS - CURRENT_COUNTER
  init_points = max(0, 20 - remaining)
  n_iter = remaining - init_points
  bo.maximize(init_points=init_points, n_iter=n_iter)
  print(bo.res)

if __name__ == '__main__':
  main()
